# Generated by Django 4.2.7 on 2025-02-19 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_favorites_pub_date_alter_favorites_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'default_related_name': 'favorites', 'verbose_name': 'Избранное'},
        ),
    ]
