# Generated by Django 4.2.7 on 2025-02-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_ingredientinrecipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'verbose_name': 'Количество ингредиента'},
        ),
    ]
