# Generated by Django 4.2.7 on 2025-02-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_ingredientinrecipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='api.IngredientInRecipe', to='api.ingredient'),
        ),
    ]
