MAX_NAME_LENGTH = 256
MAX_SLUG_NAME = 50
INGREDIENT_MIN_AMOUNT_ERROR = (
    'Количество ингредиентов не может быть меньше {min_value}!'
)
MAX_LENGTH_USER = 150
MAX_LENGTH_TAGINGREDIENT = 200
MAX_LENGTH_TAG = 32
MAX_LENGTH_RECIPE = 64
MAX_LENGTH_USER_EMAIL = 254
